'use client'

import { useState, useEffect } from 'react'
import {
  BarChart, Bar, LineChart, Line, PieChart, Pie, Cell,
  XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer
} from 'recharts'

// Import static data (will be generated by sync script)
import statsData from '../data/stats.json'

function formatNumber(n: number): string {
  if (n >= 1e9) return (n / 1e9).toFixed(1) + 'B'
  if (n >= 1e6) return (n / 1e6).toFixed(1) + 'M'
  if (n >= 1e3) return (n / 1e3).toFixed(1) + 'K'
  return n?.toLocaleString() || '0'
}

const COLORS = ['#fff', '#ccc', '#999', '#666', '#444']

export default function HomePage() {
  const [activeTab, setActiveTab] = useState('overview')
  const [soData, setSoData] = useState<any>(null)

  // Load StackOverflow data client-side
  useEffect(() => {
    fetch('https://api.stackexchange.com/2.3/users/641766?site=stackoverflow')
      .then(r => r.json())
      .then(data => {
        if (data.items?.[0]) setSoData(data.items[0])
      })
      .catch(console.error)
  }, [])

  const tabs = [
    { id: 'overview', label: 'Overview' },
    { id: 'code', label: 'Code' },
    { id: 'music', label: 'Music' },
    { id: 'social', label: 'Social' },
  ]

  return (
    <main className="container">
      {/* Hero */}
      <section className="hero">
        <img
          className="avatar"
          src="https://github.com/zeekay.png"
          alt="Zach Kelling"
          width={180}
          height={180}
        />
        <h1>Zach Kelling</h1>
        <p className="subtitle">Software Engineer · AI Enthusiast · Music Producer</p>

        <div className="social-links">
          <a href="https://github.com/zeekay" target="_blank" rel="noopener noreferrer">
            <svg viewBox="0 0 24 24" fill="currentColor"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>
            GitHub
          </a>
          <a href="https://x.com/zeekay" target="_blank" rel="noopener noreferrer">𝕏</a>
          <a href="https://linkedin.com/in/zeekay" target="_blank" rel="noopener noreferrer">LinkedIn</a>
          <a href="https://facebook.com/zeekay" target="_blank" rel="noopener noreferrer">Facebook</a>
          <a href="https://instagram.com/zeekayai" target="_blank" rel="noopener noreferrer">Instagram</a>
          <a href="https://open.spotify.com/user/zeek4y" target="_blank" rel="noopener noreferrer">Spotify</a>
          <a href="https://soundcloud.com/zeekay" target="_blank" rel="noopener noreferrer">SoundCloud</a>
          <a href="https://stackoverflow.com/users/641766/zach-kelling" target="_blank" rel="noopener noreferrer">StackOverflow</a>
        </div>
      </section>

      {/* Tabs */}
      <div className="tabs">
        {tabs.map(tab => (
          <button
            key={tab.id}
            className={`tab-btn ${activeTab === tab.id ? 'active' : ''}`}
            onClick={() => setActiveTab(tab.id)}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* Overview Tab */}
      {activeTab === 'overview' && (
        <>
          {/* GitHub Stats */}
          <section className="stats-section">
            <div className="section-header">
              <h2>📊 GitHub</h2>
              <a href="https://github.com/zeekay" className="view-all" target="_blank">View Profile →</a>
            </div>
            <div className="stats-grid">
              <div className="stat-card">
                <div className="value">{formatNumber(statsData.github.totalCommits)}</div>
                <div className="label">Commits</div>
              </div>
              <div className="stat-card">
                <div className="value">{formatNumber(statsData.github.repos)}</div>
                <div className="label">Repositories</div>
              </div>
              <div className="stat-card">
                <div className="value">{formatNumber(statsData.github.netLoc)}</div>
                <div className="label">Lines of Code</div>
              </div>
              <div className="stat-card">
                <div className="value">{statsData.github.yearsCoding}</div>
                <div className="label">Years Coding</div>
              </div>
            </div>
          </section>

          {/* AI Stats */}
          <section className="stats-section">
            <div className="section-header">
              <h2>🤖 AI Usage</h2>
            </div>
            <div className="stats-grid">
              <div className="stat-card">
                <div className="value">{formatNumber(statsData.ai.interactions)}</div>
                <div className="label">Interactions</div>
              </div>
              <div className="stat-card">
                <div className="value">{formatNumber(statsData.ai.inputTokens)}</div>
                <div className="label">Input Tokens</div>
              </div>
              <div className="stat-card">
                <div className="value">{formatNumber(statsData.ai.outputTokens)}</div>
                <div className="label">Output Tokens</div>
              </div>
              <div className="stat-card">
                <div className="value">{statsData.ai.activeDays}</div>
                <div className="label">Active Days</div>
              </div>
            </div>

            <div className="charts-grid">
              <div className="chart-container">
                <h3>Usage by Model</h3>
                <ResponsiveContainer width="100%" height={200}>
                  <PieChart>
                    <Pie
                      data={statsData.ai.byModel}
                      dataKey="tokens"
                      nameKey="model"
                      cx="50%"
                      cy="50%"
                      outerRadius={80}
                      label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`}
                    >
                      {statsData.ai.byModel.map((_, i) => (
                        <Cell key={i} fill={COLORS[i % COLORS.length]} />
                      ))}
                    </Pie>
                    <Tooltip />
                  </PieChart>
                </ResponsiveContainer>
              </div>
              <div className="chart-container">
                <h3>Daily Token Usage</h3>
                <ResponsiveContainer width="100%" height={200}>
                  <BarChart data={statsData.ai.daily.slice(-30)}>
                    <XAxis dataKey="date" tick={{ fill: '#888', fontSize: 10 }} />
                    <YAxis tick={{ fill: '#888', fontSize: 10 }} />
                    <Tooltip />
                    <Bar dataKey="tokens" fill="rgba(255,255,255,0.7)" />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </div>
          </section>

          {/* StackOverflow */}
          <section className="stats-section">
            <div className="section-header">
              <h2>💡 StackOverflow</h2>
              <a href="https://stackoverflow.com/users/641766/zach-kelling" className="view-all" target="_blank">View Profile →</a>
            </div>
            <div className="embed-card" style={{ padding: '1.5rem' }}>
              <div className="so-stats">
                <div className="so-stat">
                  <div className="value">{soData ? formatNumber(soData.reputation) : '-'}</div>
                  <div className="label">Reputation</div>
                </div>
                <div className="so-stat">
                  <div className="value">{soData ? formatNumber(soData.answer_count) : '-'}</div>
                  <div className="label">Answers</div>
                </div>
                <div className="so-stat">
                  <div className="value">{soData ? formatNumber(soData.question_count) : '-'}</div>
                  <div className="label">Questions</div>
                </div>
              </div>
              <div className="badge-row">
                <span className="badge badge-gold">🥇 {soData?.badge_counts?.gold || '-'}</span>
                <span className="badge badge-silver">🥈 {soData?.badge_counts?.silver || '-'}</span>
                <span className="badge badge-bronze">🥉 {soData?.badge_counts?.bronze || '-'}</span>
              </div>
            </div>
          </section>
        </>
      )}

      {/* Code Tab */}
      {activeTab === 'code' && (
        <section className="stats-section">
          <div className="section-header">
            <h2>📈 Coding Activity</h2>
          </div>
          <div className="charts-grid">
            <div className="chart-container">
              <h3>Commits Over Time</h3>
              <ResponsiveContainer width="100%" height={250}>
                <BarChart data={statsData.github.monthlyCommits}>
                  <XAxis dataKey="month" tick={{ fill: '#888', fontSize: 10 }} />
                  <YAxis tick={{ fill: '#888', fontSize: 10 }} />
                  <Tooltip />
                  <Bar dataKey="commits" fill="rgba(255,255,255,0.7)" />
                </BarChart>
              </ResponsiveContainer>
            </div>
            <div className="chart-container">
              <h3>Day of Week</h3>
              <ResponsiveContainer width="100%" height={250}>
                <BarChart data={statsData.github.byDayOfWeek}>
                  <XAxis dataKey="day" tick={{ fill: '#888', fontSize: 10 }} />
                  <YAxis tick={{ fill: '#888', fontSize: 10 }} />
                  <Tooltip />
                  <Bar dataKey="commits" fill="rgba(255,255,255,0.7)" />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>
          <div className="charts-grid">
            <div className="chart-container">
              <h3>Top Repositories</h3>
              <ResponsiveContainer width="100%" height={300}>
                <BarChart data={statsData.github.topRepos} layout="vertical">
                  <XAxis type="number" tick={{ fill: '#888', fontSize: 10 }} />
                  <YAxis dataKey="repo" type="category" width={120} tick={{ fill: '#888', fontSize: 10 }} />
                  <Tooltip />
                  <Bar dataKey="commits" fill="rgba(255,255,255,0.7)" />
                </BarChart>
              </ResponsiveContainer>
            </div>
            <div className="chart-container">
              <h3>Lines of Code Over Time</h3>
              <ResponsiveContainer width="100%" height={300}>
                <LineChart data={statsData.github.cumulativeLoc}>
                  <XAxis dataKey="month" tick={{ fill: '#888', fontSize: 10 }} />
                  <YAxis tick={{ fill: '#888', fontSize: 10 }} />
                  <Tooltip />
                  <Line type="monotone" dataKey="loc" stroke="#fff" strokeWidth={2} dot={false} />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </div>
        </section>
      )}

      {/* Music Tab */}
      {activeTab === 'music' && (
        <>
          <section className="stats-section">
            <div className="section-header">
              <h2>🎵 SoundCloud Likes</h2>
              <a href="https://soundcloud.com/zeekay" className="view-all" target="_blank">@zeekay →</a>
            </div>
            <div className="embed-card">
              <iframe
                width="100%"
                height="450"
                scrolling="no"
                frameBorder="no"
                allow="autoplay"
                src="https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/zeekay/likes&color=%23ffffff&auto_play=false&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"
              />
            </div>
          </section>

          <section className="stats-section">
            <div className="section-header">
              <h2>🎧 Spotify</h2>
              <a href="https://open.spotify.com/user/zeek4y" className="view-all" target="_blank">zeek4y →</a>
            </div>
            <div className="embed-grid">
              <div className="embed-card" style={{ padding: '1.5rem', textAlign: 'center' }}>
                <p style={{ color: 'var(--muted-foreground)', marginBottom: '1rem' }}>Listen on Spotify</p>
                <a
                  href="https://open.spotify.com/user/zeek4y"
                  target="_blank"
                  style={{
                    display: 'inline-flex',
                    alignItems: 'center',
                    gap: '0.5rem',
                    padding: '0.75rem 1.5rem',
                    background: '#1DB954',
                    color: '#000',
                    borderRadius: '2rem',
                    fontWeight: 600,
                  }}
                >
                  <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor"><path d="M12 0C5.4 0 0 5.4 0 12s5.4 12 12 12 12-5.4 12-12S18.66 0 12 0zm5.521 17.34c-.24.359-.66.48-1.021.24-2.82-1.74-6.36-2.101-10.561-1.141-.418.122-.779-.179-.899-.539-.12-.421.18-.78.54-.9 4.56-1.021 8.52-.6 11.64 1.32.42.18.479.659.301 1.02zm1.44-3.3c-.301.42-.841.6-1.262.3-3.239-1.98-8.159-2.58-11.939-1.38-.479.12-1.02-.12-1.14-.6-.12-.48.12-1.021.6-1.141C9.6 9.9 15 10.561 18.72 12.84c.361.181.54.78.241 1.2zm.12-3.36C15.24 8.4 8.82 8.16 5.16 9.301c-.6.179-1.2-.181-1.38-.721-.18-.601.18-1.2.72-1.381 4.26-1.26 11.28-1.02 15.721 1.621.539.3.719 1.02.419 1.56-.299.421-1.02.599-1.559.3z"/></svg>
                  Follow on Spotify
                </a>
                <p style={{ color: 'var(--muted-foreground)', fontSize: '0.75rem', marginTop: '1rem' }}>
                  Spotify user profiles cannot be embedded directly.<br />
                  Click above to see playlists and listening activity.
                </p>
              </div>
              <div className="embed-card">
                <iframe
                  width="100%"
                  height="352"
                  scrolling="no"
                  frameBorder="no"
                  allow="autoplay"
                  src="https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/zeekay/sets&color=%23ffffff&auto_play=false&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"
                />
              </div>
            </div>
          </section>

          <section className="stats-section">
            <div className="section-header">
              <h2>🎹 My Tracks</h2>
            </div>
            <div className="embed-card">
              <iframe
                width="100%"
                height="450"
                scrolling="no"
                frameBorder="no"
                allow="autoplay"
                src="https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/zeekay/tracks&color=%23ffffff&auto_play=false&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false"
              />
            </div>
          </section>
        </>
      )}

      {/* Social Tab */}
      {activeTab === 'social' && (
        <>
          <section className="stats-section">
            <div className="section-header">
              <h2>📸 Instagram</h2>
              <a href="https://instagram.com/zeekayai" className="view-all" target="_blank">@zeekayai →</a>
            </div>
            <div className="embed-card" style={{ padding: '1.5rem', textAlign: 'center' }}>
              <p style={{ color: 'var(--muted-foreground)', marginBottom: '1rem' }}>Latest posts from Instagram</p>
              <a
                href="https://instagram.com/zeekayai"
                target="_blank"
                style={{
                  display: 'inline-block',
                  padding: '0.75rem 1.5rem',
                  border: '1px solid var(--border)',
                  borderRadius: 'var(--radius)',
                }}
              >
                View @zeekayai on Instagram →
              </a>
            </div>
          </section>

          <section className="stats-section">
            <div className="section-header">
              <h2>💼 LinkedIn</h2>
              <a href="https://linkedin.com/in/zeekay" className="view-all" target="_blank">View Profile →</a>
            </div>
            <div className="embed-card" style={{ padding: '1.5rem', textAlign: 'center' }}>
              <a
                href="https://linkedin.com/in/zeekay"
                target="_blank"
                style={{
                  display: 'inline-block',
                  padding: '0.75rem 1.5rem',
                  border: '1px solid var(--border)',
                  borderRadius: 'var(--radius)',
                }}
              >
                View LinkedIn Profile →
              </a>
            </div>
          </section>
        </>
      )}

      {/* Footer */}
      <footer>
        <div className="links">
          <a href="https://github.com/zeekay/home" target="_blank">⭐ Star</a> ·{' '}
          <a href="https://github.com/zeekay/home/fork" target="_blank">🍴 Fork</a> ·{' '}
          <a href="https://github.com/zeekay/home" target="_blank">Source</a>
        </div>
        <p>Crafted with ❤️ by <a href="https://zeekay.ai">Zach Kelling</a></p>
        <p style={{ marginTop: '0.5rem' }}>BSD-3-Clause © Zach Kelling</p>
        <p style={{ marginTop: '1rem', fontSize: '0.7rem' }}>
          Last updated: {new Date().toLocaleDateString()} · Data refreshed daily via GitHub Actions
        </p>
      </footer>
    </main>
  )
}
